// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykbtzvhbqkyorteokjop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrYnR6dmhicWt5b3J0ZW9ram9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNjE2OTMsImV4cCI6MjA1MzgzNzY5M30.65j4MXhZuuMEyR5raE1djd_fSBnQSA-xFjCCNgsX5xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);